// coped-pulse/resources/js/Pages/Learner/Course/Learn.vue
<script setup>
import { ref, computed } from 'vue';
import { Head } from '@inertiajs/vue3';
import { Link } from '@inertiajs/vue3';

const props = defineProps({
    course: Object,
    enrollment: Object,
});

const currentModuleIndex = ref(0);
const currentLessonIndex = ref(0);

const currentModule = computed(() => props.course.modules[currentModuleIndex.value] || null);
const currentLesson = computed(() => currentModule.value?.lessons[currentLessonIndex.value] || null);

const nextLesson = () => {
    if (currentModule.value && currentLessonIndex.value < currentModule.value.lessons.length - 1) {
        currentLessonIndex.value++;
    } else if (currentModuleIndex.value < props.course.modules.length - 1) {
        currentModuleIndex.value++;
        currentLessonIndex.value = 0;
    }
};

const prevLesson = () => {
    if (currentLessonIndex.value > 0) {
        currentLessonIndex.value--;
    } else if (currentModuleIndex.value > 0) {
        currentModuleIndex.value--;
        currentLessonIndex.value = props.course.modules[currentModuleIndex.value].lessons.length - 1;
    }
};

const selectLesson = (moduleIndex, lessonIndex) => {
    currentModuleIndex.value = moduleIndex;
    currentLessonIndex.value = lessonIndex;
};
</script>

<template>
    <Head :title="course.title" />

    <div class="min-h-screen bg-gray-50 flex">
        <!-- Sidebar -->
        <aside class="w-72 bg-white border-r border-gray-200 hidden lg:block flex flex-col">
            <div class="p-4 border-b border-gray-200">
                <h2 class="text-lg font-semibold text-gray-900">{{ course.title }}</h2>
                <div class="mt-2 h-2 bg-gray-200 rounded-full overflow-hidden">
                    <div
                        class="bg-indigo-600 h-full transition-all duration-300"
                        :style="{ width: enrollment.progress + '%' }"
                    />
                </div>
                <p class="text-xs text-gray-500 mt-1">{{ enrollment.progress }}% complete</p>
            </div>

            <nav class="flex-1 overflow-y-auto p-4">
                <div v-for="(module, mIndex) in course.modules" :key="module.id" class="mb-4">
                    <h3 class="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">
                        {{ module.title }}
                    </h3>
                    <ul class="space-y-1 ml-2">
                        <li v-for="(lesson, lIndex) in module.lessons" :key="lesson.id">
                            <button
                                @click="selectLesson(mIndex, lIndex)"
                                :class="[
                                    'w-full text-left px-3 py-2 text-sm rounded-lg transition-colors',
                                    mIndex === currentModuleIndex && lIndex === currentLessonIndex
                                        ? 'bg-indigo-50 text-indigo-700 font-medium'
                                        : 'text-gray-600 hover:bg-gray-50',
                                ]"
                            >
                                <span class="flex items-center">
                                    <svg v-if="lesson.content_type === 'video'" class="w-4 h-4 mr-2 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                                        <path d="M6.3 2.841A1.5 1.5 0 004 4.11V15.89a1.5 1.5 0 002.3 1.269l9.344-5.89a1.5 1.5 0 000-2.538L6.3 2.84z" />
                                    </svg>
                                    <svg v-else-if="lesson.content_type === 'pdf'" class="w-4 h-4 mr-2 text-red-500" fill="currentColor" viewBox="0 0 20 20">
                                        <path d="M4 4a2 2 0 00-2 2v12a2 2 0 002 2h12a2 2 0 002-2V8.414A2 2 0 0015.586 6L11.414 2A2 2 0 0010 2H4z" />
                                    </svg>
                                    <svg v-else class="w-4 h-4 mr-2 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                                        <path d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z" />
                                    </svg>
                                    {{ lesson.title }}
                                </span>
                            </button>
                        </li>
                    </ul>
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="flex-1 flex flex-col min-w-0">
            <div class="p-4 border-b border-gray-200 lg:p-6">
                <Link
                    :href="route('portal')"
                    class="text-sm text-gray-500 hover:text-gray-700 mb-4 inline-block"
                >
                    ← Back to Portal
                </Link>
                <div class="flex items-center justify-between">
                    <div>
                        <h1 class="text-2xl font-bold text-gray-900">{{ course.title }}</h1>
                        <p class="text-gray-500 mt-1">{{ currentModule?.title }} / {{ currentLesson?.title }}</p>
                    </div>
                    <div class="flex space-x-2">
                        <button
                            @click="prevLesson"
                            :disabled="currentModuleIndex === 0 && currentLessonIndex === 0"
                            class="px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 disabled:opacity-50"
                        >
                            Previous
                        </button>
                        <button
                            @click="nextLesson"
                            :disabled="currentModuleIndex === course.modules.length - 1 && currentLessonIndex === course.modules[currentModuleIndex].lessons.length - 1"
                            class="px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50"
                        >
                            Next
                        </button>
                    </div>
                </div>
            </div>

            <div class="flex-1 overflow-y-auto p-4 lg:p-6">
                <div v-if="currentLesson" class="max-w-3xl mx-auto">
                    <div class="mb-6">
                        <span
                            :class="[
                                'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium',
                                currentLesson.content_type === 'video' ? 'bg-purple-100 text-purple-800' : '',
                                currentLesson.content_type === 'pdf' ? 'bg-red-100 text-red-800' : '',
                                currentLesson.content_type === 'text' ? 'bg-gray-100 text-gray-800' : '',
                            ]"
                        >
                            {{ currentLesson.content_type }}
                        </span>
                        <span v-if="currentLesson.duration" class="ml-2 text-sm text-gray-500">{{ currentLesson.duration }} min</span>
                    </div>

                    <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
                        <h2 class="text-xl font-semibold text-gray-900 mb-4">{{ currentLesson.title }}</h2>

                        <div v-if="currentLesson.content_type === 'video'">
                            <div class="aspect-video bg-gray-900 rounded-lg overflow-hidden relative">
                                <iframe
                                    v-if="currentLesson.content_url"
                                    :src="currentLesson.content_url"
                                    class="absolute inset-0 w-full h-full"
                                    frameborder="0"
                                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                    allowfullscreen
                                />
                                <div v-else class="absolute inset-0 flex items-center justify-center text-gray-400">
                                    Video URL not provided
                                </div>
                            </div>
                        </div>

                        <div v-else-if="currentLesson.content_type === 'pdf'">
                            <div class="aspect-[4/3] bg-gray-100 rounded-lg overflow-hidden relative">
                                <iframe
                                    v-if="currentLesson.content_url"
                                    :src="currentLesson.content_url"
                                    class="absolute inset-0 w-full h-full"
                                    frameborder="0"
                                />
                                <div v-else class="absolute inset-0 flex items-center justify-center text-gray-400">
                                    PDF URL not provided
                                </div>
                            </div>
                        </div>

                        <div v-else>
                            <div class="prose max-w-none text-gray-700" v-html="currentLesson.content || '<p class=\'text-gray-400\'>No content available</p>'" />
                        </div>
                    </div>
                </div>

                <div v-else class="text-center py-12">
                    <p class="text-gray-500">No lesson selected</p>
                </div>
            </div>
        </main>
    </div>
</template>

// coped-pulse/resources/js/Pages/design_v1/Learner/Course/Learn.jsx
import { Head, Link } from '@inertiajs/react';
import LearnerLayout from '@/Layouts/design_v1/LearnerLayout';

/**
 * Only allow http(s) URLs to be rendered as links.
 * Prevents javascript:/data: URLs (stored XSS) from becoming clickable.
 */
const safeMediaUrl = (url) => {
    if (!url || typeof url !== 'string') return null;
    try {
        const parsed = new URL(url.trim());
        return parsed.protocol === 'http:' || parsed.protocol === 'https:' ? parsed.href : null;
    } catch {
        return null;
    }
};

export default function Learn({ course, enrollment }) {
    const modules = course.modules || [];

    return (
        <LearnerLayout>
            <Head title={`Learn: ${course.title}`} />

            <div className="max-w-5xl mx-auto space-y-8">
                {/* Course Header */}
                <div className="bg-white/80 backdrop-blur-md shadow-sm border border-gray-100 rounded-3xl p-8 relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-50 rounded-full mix-blend-multiply filter blur-3xl opacity-50 -translate-y-1/2 translate-x-1/2"></div>

                    <Link
                        href={route('portal')}
                        className="inline-flex items-center text-sm font-semibold text-indigo-600 hover:text-indigo-700 mb-6 transition-colors relative z-10"
                    >
                        <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" /></svg>
                        Back to Portal
                    </Link>

                    <div className="relative z-10 flex flex-col md:flex-row md:items-start justify-between gap-6">
                        <div className="flex-1">
                            <h1 className="text-4xl font-black text-gray-900 tracking-tight mb-3">
                                {course.title}
                            </h1>
                            {course.description && (
                                <p className="text-lg text-gray-600 leading-relaxed max-w-3xl">
                                    {course.description}
                                </p>
                            )}
                        </div>
                        <div className="flex flex-col items-start md:items-end space-y-3 shrink-0">
                            <span className={`inline-flex items-center px-4 py-1.5 rounded-full text-sm font-bold shadow-sm ${
                                enrollment?.completed_at
                                    ? 'bg-green-100/90 text-green-800 border border-green-200'
                                    : 'bg-blue-100/90 text-blue-800 border border-blue-200'
                            }`}>
                                {enrollment?.completed_at ? 'COMPLETED' : 'IN PROGRESS'}
                            </span>
                            <div className="text-sm text-gray-500 font-medium bg-gray-50 px-4 py-2 rounded-xl border border-gray-100">
                                {modules.length} {modules.length === 1 ? 'Module' : 'Modules'}
                            </div>
                        </div>
                    </div>
                </div>

                {/* Modules List */}
                {modules.length > 0 ? (
                    <div className="space-y-4">
                        {modules.map((module, index) => {
                            const mediaUrl = safeMediaUrl(module.media_url);

                            return (
                                <article
                                    key={module.id}
                                    className="group bg-white rounded-2xl border border-gray-100 shadow-sm hover:shadow-md hover:border-indigo-100 transition-all duration-300 p-6 flex gap-5"
                                >
                                    <div className="shrink-0 w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-600 to-purple-600 text-white font-bold text-lg flex items-center justify-center shadow-md group-hover:scale-105 transition-transform duration-300">
                                        {index + 1}
                                    </div>

                                    <div className="flex-1 min-w-0">
                                        <h2 className="text-xl font-bold text-gray-900 break-words">
                                            {module.title}
                                        </h2>

                                        {module.description && (
                                            <p className="mt-2 text-gray-500 leading-relaxed whitespace-pre-line break-words">
                                                {module.description}
                                            </p>
                                        )}

                                        {mediaUrl && (
                                            <a
                                                href={mediaUrl}
                                                target="_blank"
                                                rel="noopener noreferrer"
                                                className="mt-5 inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-semibold shadow-md hover:shadow-lg hover:-translate-y-0.5 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 transition-all duration-200"
                                            >
                                                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                                                View Media
                                                <svg className="w-4 h-4 opacity-80" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" /></svg>
                                            </a>
                                        )}
                                    </div>
                                </article>
                            );
                        })}
                    </div>
                ) : (
                    <div className="text-center py-20 bg-white/50 backdrop-blur-sm rounded-3xl border border-gray-100 border-dashed">
                        <svg className="w-16 h-16 text-gray-300 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 002-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" /></svg>
                        <p className="text-lg text-gray-500 font-medium">No modules available yet.</p>
                        <p className="text-sm text-gray-400 mt-2">Check back later once the instructor adds content.</p>
                    </div>
                )}
            </div>
        </LearnerLayout>
    );
}
