// coped-pulse/resources/js/Pages/Learner/Portal.vue
<script setup>
import { Head } from '@inertiajs/vue3';

const props = defineProps({
    enrollments: Object,
});
</script>

<template>
    <Head title="My Learning Portal" />

    <div class="min-h-screen bg-gray-50">
        <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
            <div class="mb-6">
                <h1 class="text-3xl font-bold text-gray-900">My Learning Portal</h1>
                <p class="mt-1 text-gray-500">Continue your learning journey</p>
            </div>

            <div v-if="enrollments.data.length === 0" class="text-center py-12">
                <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                </svg>
                <h3 class="mt-2 text-sm font-medium text-gray-900">No enrolled courses</h3>
                <p class="mt-1 text-sm text-gray-500">Browse the catalog to enroll in courses.</p>
            </div>

            <div v-else class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
                <div v-for="enrollment in enrollments.data" :key="enrollment.id" class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden hover:shadow-md transition-shadow">
                    <div class="p-6">
                        <div class="flex items-start justify-between">
                            <div class="flex-1 min-w-0">
                                <h3 class="text-lg font-medium text-gray-900 truncate">{{ enrollment.course.title }}</h3>
                                <p v-if="enrollment.course.description" class="mt-1 text-sm text-gray-500 line-clamp-2">{{ enrollment.course.description }}</p>
                            </div>
                        </div>

                        <div class="mt-4">
                            <div class="flex items-center justify-between text-sm mb-1">
                                <span class="text-gray-500">Progress</span>
                                <span class="font-medium text-gray-900">{{ enrollment.progress }}%</span>
                            </div>
                            <div class="w-full bg-gray-200 rounded-full h-2">
                                <div
                                    class="bg-indigo-600 h-2 rounded-full transition-all duration-300"
                                    :style="{ width: enrollment.progress + '%' }"
                                />
                            </div>
                        </div>

                        <div class="mt-4">
                            <a
                                :href="route('learner.course.learn', enrollment.course)"
                                class="inline-flex items-center w-full justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700"
                            >
                                {{ enrollment.progress > 0 ? 'Continue Learning' : 'Start Learning' }}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

// coped-pulse/resources/js/Pages/design_v1/Learner/Portal.jsx
import { Head, Link } from '@inertiajs/react';
import LearnerLayout from '@/Layouts/design_v1/LearnerLayout';

export default function Portal({ enrollments }) {
    return (
        <LearnerLayout>
            <Head title="My Learning Portal" />
            
            <div className="mb-10 text-center md:text-left">
                <h1 className="text-4xl md:text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-indigo-800 to-purple-700 tracking-tight mb-4">
                    My Learning Portal
                </h1>
                <p className="text-lg text-gray-600 max-w-2xl leading-relaxed">
                    Welcome back! Here are the courses you are currently enrolled in.
                </p>
            </div>

            {enrollments.data.length === 0 ? (
                <div className="flex flex-col items-center justify-center py-20 bg-white/50 backdrop-blur-sm rounded-3xl border border-gray-100 shadow-sm">
                    <svg className="w-16 h-16 text-gray-300 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                    </svg>
                    <p className="text-xl text-gray-500 font-medium mb-6">You are not enrolled in any courses yet.</p>
                    <Link
                        href={route('learner.catalog')}
                        className="px-6 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-full font-bold shadow-md hover:shadow-lg transform hover:-translate-y-0.5 transition-all duration-200"
                    >
                        Browse Course Catalog
                    </Link>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                    {enrollments.data.map(enrollment => (
                        <div 
                            key={enrollment.id} 
                            className="group flex flex-col bg-white rounded-3xl overflow-hidden border border-gray-100 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300"
                        >
                            <div className="h-40 bg-gradient-to-br from-indigo-100 to-purple-100 flex items-center justify-center p-6 relative overflow-hidden">
                                <div className="absolute inset-0 bg-indigo-500/5 mix-blend-overlay group-hover:bg-indigo-500/10 transition-colors duration-300"></div>
                                <h3 className="text-xl font-bold text-indigo-900 text-center relative z-10 group-hover:scale-105 transition-transform duration-300">
                                    {enrollment.course?.title}
                                </h3>
                                
                                <div className="absolute top-4 right-4 z-20">
                                    <span className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-bold shadow-sm backdrop-blur-md ${
                                        enrollment.completed_at
                                            ? 'bg-green-100/90 text-green-800 border border-green-200'
                                            : 'bg-blue-100/90 text-blue-800 border border-blue-200'
                                    }`}>
                                        {enrollment.completed_at ? 'COMPLETED' : 'ENROLLED'}
                                    </span>
                                </div>
                            </div>
                            
                            <div className="p-8 flex flex-col flex-grow">
                                <div className="flex items-center space-x-3 mb-4">
                                    <div className="w-8 h-8 rounded-full bg-gradient-to-r from-purple-500 to-indigo-500 flex items-center justify-center text-white font-bold text-xs shadow-md">
                                        {enrollment.course?.instructor?.name?.charAt(0)}
                                    </div>
                                    <span className="text-sm font-semibold text-gray-700">
                                        {enrollment.course?.instructor?.name || 'Instructor'}
                                    </span>
                                </div>

                                {/* Progress line */}
                                <div className="mb-6">
                                    <div className="flex items-center justify-between mb-1.5">
                                        <span className="text-xs font-bold text-gray-600">Progress</span>
                                        <span className={`text-xs font-bold ${enrollment.completed_at ? 'text-green-700' : 'text-indigo-700'}`}>
                                            {Math.min(100, Math.max(0, Math.round(Number(enrollment.progress ?? 0))))}%
                                        </span>
                                    </div>
                                    <div
                                        className="w-full h-2 bg-gray-100 rounded-full overflow-hidden"
                                        role="progressbar"
                                        aria-valuenow={Math.round(Number(enrollment.progress ?? 0))}
                                        aria-valuemin={0}
                                        aria-valuemax={100}
                                        aria-label={`Progress for ${enrollment.course?.title}`}
                                    >
                                        <div
                                            className={`h-full rounded-full transition-all ${
                                                enrollment.completed_at
                                                    ? 'bg-gradient-to-r from-green-500 to-emerald-500'
                                                    : 'bg-gradient-to-r from-indigo-600 to-purple-600'
                                            }`}
                                            style={{ width: `${Math.min(100, Math.max(0, Math.round(Number(enrollment.progress ?? 0))))}%` }}
                                        />
                                    </div>
                                </div>
                                
                                <div className="flex-grow"></div>
                                
                                <Link
                                    href={route('learner.course.learn', enrollment.course)}
                                    className="w-full py-3.5 px-4 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-2xl font-bold text-sm shadow-md hover:shadow-lg hover:from-indigo-500 hover:to-purple-500 transform hover:-translate-y-0.5 transition-all duration-200 active:scale-95 flex justify-center items-center space-x-2"
                                >
                                    <span>Continue Learning</span>
                                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 5l7 7m0 0l-7 7m7-7H3" />
                                    </svg>
                                </Link>
                            </div>
                        </div>
                    ))}
                </div>
            )}

            {/* Pagination */}
            {enrollments.links && enrollments.links.length > 3 && (
                <div className="mt-12 flex justify-center space-x-2">
                    {enrollments.links.map((link, i) => (
                        link.url ? (
                            <Link
                                key={i}
                                href={link.url}
                                className={`px-4 py-2 rounded-xl text-sm font-medium transition-all duration-200 ${
                                    link.active 
                                        ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-md' 
                                        : 'bg-white text-gray-700 border border-gray-200 hover:bg-indigo-50 hover:text-indigo-600 hover:border-indigo-200'
                                }`}
                                dangerouslySetInnerHTML={{ __html: link.label }}
                            />
                        ) : (
                            <span
                                key={i}
                                className="px-4 py-2 rounded-xl text-sm font-medium bg-gray-50 text-gray-400 border border-gray-100"
                                dangerouslySetInnerHTML={{ __html: link.label }}
                            />
                        )
                    ))}
                </div>
            )}
        </LearnerLayout>
    );
}
